### ISSUE TITLE
Server has the incorrect port

### ISSUE THREAD

**Issue by codebubb** [PJMantoss/recipe_search#1]
Hi, think you deleted your YouTube comment and you might have already worked this out but your server is listening on port 3001 but your fetch request is accessing localhost:3000 so this needs to be updated to `localhost:3001`.

https://github.com/PJMantoss/recipe_search/blob/main/src/App.tsx#L11

Hope it helps.

**Comment by PJMantoss** [comment]
Thank you James for your reply.

I changed my fetch request to *localhost:3001* just like in *server.js*
But it's still not working. I now have new errors in the console. Kindly
see attached images.
I suspect the problem is in package.json, I may be missing some
dependencies.
Your codes on github has this line under *"scripts"* in package.json which
I don't have in mine: *"api:serve": "node server"*

Please, what dependency do I have to install to get the resources loading?

Thank you.

Joel

**Comment by codebubb** [comment]
Hey Joel,

I've cloned your project and it's working OK for me (albeit a few tweaks and CSS etc).

You'll need to run the `server.js` file to setup the proxy before running the React app.  You can do this with just `node server.js` when your terminal is in the project directory (the scripts I had in the `package.json` just did a similar thing).  

Hope that gets it working for you.

**Comment by PJMantoss** [comment]
Hi James!
It worked!
I started the server.js file first before running the React app.
Thanks a lot for your help.

Do you have any premium courses on Typescript/React or React/Node? I Would
love to subscribe.

Thank you

Joel

**Comment by codebubb** [comment]
Hey Joel, glad to hear it's working for you now!

I don't currently have any courses for sale at the moment - just been focusing on YouTube tutorials and don't have much time for anything else!. I think I'll be doing a course (on YouTube) in the upcoming weeks focusing solely on TypeScript so hopefully that will be useful for you.

All the best!
